### ISSUE TITLE
Do not pan while typing in canvas shape

### ISSUE THREAD

**Issue by nathonius** [nathonius/obsidian-canvas-pan#3]
While typing in a note embedded in a canvas, the keyboard pan does not activate. However, it does pan when typing in a shape or line label placed on the canvas.

**Comment by Droyk** [comment]
@nathonius, Still Pan's in the group name text area 
![image](https://github.com/user-attachments/assets/bfa0e40a-3a9f-45d9-b34f-eeb4903fdcc0)

![image](https://github.com/user-attachments/assets/cbe291e6-ddd9-4b39-9359-1a7856def9fd)
